apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: us-east-nginx
  namespace: staging
spec:
  interval: 15m0s
  timeout: 1m0s
  chart:
    spec:
      chart: nginx
      version: 15.1.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    service:
      type: ClusterIP